version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: .docker/Dockerfile.app
    user: "${UID-1000}:${GID-1000}"
    volumes:
      - ../app:/app
    env_file:
      - .env
    working_dir: /app
    command: "python3 scripts/main.py"
    ports:
      - "5000:5000"