version: '3.8'

services:
  arxiv-recommender:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    volumes:
      - ../app:/app
    env_file:
      - .env
    working_dir: /app
    command: "python3 main.py"